version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] 
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
        - "5432:5432"
  web:
    build: .
    container_name: user-microservice
    env_file:
      - .env
    ports:
      - "1234:1234"
    depends_on:
      - db